### ISSUE TITLE
problem: After #196 `five_mem_node` example starts to panic

### ISSUE THREAD

**Issue by 652h** [pingcap/raft-rs#209]
**Describe the bug**

Example `five_mem_node` panics:

```bash
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target\debug\examples\five_mem_node.exe`
thread '<unnamed>' panicked at ' to_commit 1 is out of range [last_index 0]', src\raft_log.rs:248:13
stack backtrace:
   0:           0xc43da4 - std::sys_common::backtrace::_print::h0d23e7cf94acf3e8
                               at src\libstd\sys\windows\backtrace/mod.rs:94
                               at src\libstd\sys\windows\backtrace/mod.rs:85
                               at src\libstd\sys_common/backtrace.rs:70
   1:           0xc46ce1 - std::panicking::default_hook::{{closure}}::h0f9e3cdf1594b3e8
                               at src\libstd\sys_common/backtrace.rs:58
                               at src\libstd/panicking.rs:200
   2:           0xc46a23 - std::panicking::default_hook::hb02a238f63a244b3
                               at src\libstd/panicking.rs:215
   3:           0xc47311 - std::panicking::rust_panic_with_hook::h81ab4f4cced1dd00
                               at src\libstd/panicking.rs:478
   4:           0xc46f3b - std::panicking::continue_panic_fmt::hf661ceea84d7935f
                               at src\libstd/panicking.rs:385
   5:           0xc46e81 - std::panicking::begin_panic_fmt::heee119e260da2827
                               at src\libstd/panicking.rs:340
   6:           0x465871 - <raft::raft_log::RaftLog<T>>::commit_to::hc4bae70ae79e9f58
                               at <::std::macros::/panic macros>:8
   7:           0x444b1e - <raft::raft::Raft<T>>::restore_raft::h9f574c2bb2856d58
                               at D:\Projects\raft-rs\src/raft.rs:2011
   8:           0x459d08 - <raft::raft::Raft<T>>::restore::h4cd7b1892be6ab07
                               at D:\Projects\raft-rs\src/raft.rs:2065
   9:           0x44a34f - <raft::raft::Raft<T>>::handle_snapshot::hb72ddee7196ffe9f
                               at D:\Projects\raft-rs\src/raft.rs:1975
  10:           0x446fdd - <raft::raft::Raft<T>>::step_follower::h7c829266b7b3a167
                               at D:\Projects\raft-rs\src/raft.rs:1849
  11:           0x459260 - <raft::raft::Raft<T>>::step::he0a5fc27ef4d7f9d
                               at D:\Projects\raft-rs\src/raft.rs:1207
  12:           0x4776c0 - <raft::raw_node::RawNode<T>>::step::he716844d3f7e5732
                               at D:\Projects\raft-rs\src/raw_node.rs:340
  13:           0x46dac9 - five_mem_node::Node::step::h33e74baa51232218
                               at examples/five_mem_node/main.rs:186
  14:           0x46ae9a - five_mem_node::main::{{closure}}::h26c223790fbba8a1
                               at examples/five_mem_node/main.rs:69
  15:           0x41c695 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3e981f1b2e98a45b
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\sys_common/backtrace.rs:135
  16:           0x415975 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h27ea7146e69ed9b3
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\thread/mod.rs:469
  17:           0x478bd5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h01d0d80c6b0902ce
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd/panic.rs:309
  18:           0x43f91b - std::panicking::try::do_call::h9057acfc5ec7945d
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd/panicking.rs:297
  19:           0xc57ef8 - _rust_maybe_catch_panic
                               at src\libpanic_unwind/lib.rs:92
  20:           0x43f802 - std::panicking::try::h5a54b76bbb74adb9
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd/panicking.rs:276
  21:           0x478c15 - std::panic::catch_unwind::h5d46699ea00b2347
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd/panic.rs:388
  22:           0x41573f - std::thread::Builder::spawn_unchecked::{{closure}}::ha9c8640d9bfa1f95
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\thread/mod.rs:468
  23:           0x415c84 - <F as alloc::boxed::FnBox<A>>::call_box::h257bc9d47b73fecc
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\liballoc/boxed.rs:734
  24:           0xc55954 - std::sys::windows::thread::Thread::new::thread_start::hb65bb7eff907a3e2
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\liballoc/boxed.rs:744
                               at src\libstd\sys_common/thread.rs:14
                               at src\libstd\sys\windows/thread.rs:47
  25:         0x77b9571c - unit_addrs_search
  26:         0x77cf385c - unit_addrs_search
```

**To Reproduce**
1. `git checkout e4041461e901f0`
2. `RUST_BACKTRACE=full cargo run --example five_mem_node`

**Expected behavior**
Before `e4041461e901f0` (#196) example run without errors.

**System information**
```
rustc 1.33.0 (2aa4c46cf 2019-02-28)
binary: rustc
commit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858
commit-date: 2019-02-28
host: x86_64-pc-windows-gnu
release: 1.33.0
LLVM version: 8.0
```

```
MINGW64_NT-6.1 652h-PC 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msy
```

**Comment by Fullstop000** [comment]
It seems that https://github.com/pingcap/raft-rs/pull/206 will fix this

**Comment by 652h** [comment]
Great, didn't see it.

**Comment by 652h** [comment]
Duplicates #205.
